# Generated by Django 6.0.3 on 2026-06-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_biografia_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia_deportiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deporte_favorito',
            field=models.CharField(blank=True, choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('tenis', 'Tenis')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='disponibilidad_habitual',
            field=models.CharField(blank=True, choices=[('semana_manana', 'Entre semana - Mañanas'), ('semana_tarde', 'Entre semana - Tardes'), ('semana_noche', 'Entre semana - Noches'), ('finde_manana', 'Fin de semana - Mañanas'), ('finde_tarde', 'Fin de semana - Tardes'), ('finde_noche', 'Fin de semana - Noches'), ('diaria', 'Todos los días')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posicion_juego',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
