# Generated by Django 6.0.3 on 2026-03-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=50)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
