# Generated by Django 6.0.3 on 2026-04-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_cancha_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('tenis', 'Tenis')], max_length=20),
        ),
    ]
