# Generated by Django 6.0.3 on 2026-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_alter_cancha_deporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
    ]
