# Generated by Django 6.0.3 on 2026-06-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_cancha_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='direccion',
            field=models.CharField(default='No especificada', max_length=255),
        ),
        migrations.AddField(
            model_name='cancha',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
