# Generated by Django 6.0.3 on 2026-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_cancha_direccion_cancha_latitud_cancha_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
