# Generated by Django 6.0.3 on 2026-03-19 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='capacidad',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='jugadores',
            field=models.ManyToManyField(blank=True, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('privada', 'Privada'), ('publica', 'Publica')], default='privada', max_length=10),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
