# Generated by Django 6.0.3 on 2026-06-19 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_cancha_direccion_cancha_latitud_cancha_longitud'),
        ('reservas', '0002_reserva_capacidad_reserva_jugadores_reserva_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='capacidad',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('cancha', 'fecha', 'hora_inicio', 'hora_fin'), name='unique_reserva_slot'),
        ),
    ]
